#!/usr/bin/env python
#encoding=utf-8
#引入模块
import urllib, urllib2, cookielib, re, sys, threading
#登录人人网需要的信息
myemail = ''
mypassword = ''
myid = '541823308'

class  Renren(threading.Thread):

    def __init__(self,email,password):
        self.email=email
        self.password=password
        self.origURL='http://www.renren.com/Home.do'
        self.domain='renren.com'
        #验证个人信息
        # 如果有本地cookie 登录时无需验证
        self.cj = cookielib.LWPCookieJar()

        try:
            self.cj.revert('renren,cookie')
        except:
            None

        self.opener = urllib2.build_opener(urllib2.HTTPCookieProcessor(self.cj))
        urllib2.install_opener(self.opener)
#此函数用于实现对人人网的登录，返回其主页
    def login(self):
        params = {'email':self.email,'password':self.password,'origURL':self.origURL,'domain':self.domain}
        req = urllib2.Request(
            'http://www.renren.com/PLogin.do',
            urllib.urlencode(params)      
        )
        r = self.opener.open(req)
#获取好友列表，并进行输出存储
    def friends(self):
        print "Get my friends"
        f = self.getmyfriends()
        print "friends list"
        print f,len(f)

        #todo
        self.todolist=f     
        self.donelist=[]

        #写入文件
        fdata=open('data00.txt','w')
        for item in f:
            fdata.write(item+' ')
        fdata.close()

    def realfun(self, x):
        filename="data"+x+'.txt'
        fp=open(filename,'w')
        
        while True:
            rrid=self.getone()    #从todo里取第一个数据
            if rrid==1:
                break
            print rrid
            f=self.getfriends(rrid)
            templst=''
            for eachid in f:
                templst=eachid+' '+templst
            #保存数据
            fp.write(rrid+'@@@@@@@@@@@@@@@\n'+templst)
            fp.write('\n')
        fp.close()
#获取好友的好友列表并输出存盘
    def realrun(self):
        th1 = threading.Thread(target=self.realfun,args=('1'))
        th2 = threading.Thread(target=self.realfun,args=('2'))
        th3 = threading.Thread(target=self.realfun,args=('3'))
        th4 = threading.Thread(target=self.realfun,args=('4'))
        th5 = threading.Thread(target=self.realfun,args=('5'))
        th6 = threading.Thread(target=self.realfun,args=('6'))
        th7 = threading.Thread(target=self.realfun,args=('7'))
        th8 = threading.Thread(target=self.realfun,args=('8'))
        th9 = threading.Thread(target=self.realfun,args=('9'))
        th1.start()
        th2.start()
        th3.start()
        th4.start()
        th5.start()
        th6.start()
        th7.start()
        th8.start()
        th9.start()

    def getfriends(self,rrid):
        friends=[]
        count=0

        while True:
            count1 = str(count)
            req="http://friend.renren.com/GetFriendList.do?curpage="+count1+'&id='+str(rrid)
            print 'Get',req
            r=self.opener.open(req)
            data=r.read()
            f=re.findall('<a id="addFriend(\d{5,15})"',data)
            friends=friends+f
            count=count+1
            if f == []:
                             return friends
#获取个人好友列表
    def getmyfriends(self):
        friends = []
        count=0
        
        while True:
            count1 = str(count)
            req="http://friend.renren.com/GetFriendList.do?curpage="+count1+'&id='+str(myid)
            print 'Get',req
            r=self.opener.open(req)
            data=r.read()
            f=re.findall('Poke.do\?id=(\d{5,15})" oncl',data)
            print f
            friends=friends+f
            count=count+1
            if f == []:
                return friends
#找到要获取好友列表的id
    def getone(self):
        if self.todolist==[]:
            print "Empty todo list"
            return 1
        popup=self.todolist[0]     #选择第一个id
        self.donelist.append(popup) #加入到done列表
        del self.todolist[0]     #在todo中删除   
        return popup             #返回      
                
if __name__ == "__main__":
    a=Renren(myemail, mypassword)
    print "your account and password are %s %s" % (myemail, mypassword)
    a.login()
    a.friends()
    a.realrun()
    

     
  
      
